db:
  dsn: "root:123456@tcp(localhost:13306)/test_db?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:16379"
  password: "123456"
  db: 0

kafka:
  addrs:
    - "localhost:9094"
    - "localhost:9095"

logger:
  mode: "prod"            # dev or prod
  log_level: "info"        # debug, info, warn, error, panic, panic, fatal
  encoding: "json"        # console or json

  # lumberjack options
  log_filename: "logs.log"
  max_size: 500            # megabytes
  max_backups: 3
  max_age: 28              # days
  compress: true