// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-layout/internal/core/repo"
	"basic-layout/internal/core/repo/dao"
	"basic-layout/internal/core/svc"
	"basic-layout/internal/infra"
	"basic-layout/internal/web"
	"basic-layout/internal/web/handler"
	"basic-layout/pkg/logger"
	"github.com/gin-gonic/gin"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// runApp init server application.
func runApp(log logger.Logger) *gin.Engine {
	handlersChain := web.InitMiddlewares()
	db := infra.InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repo.NewUserRepository(userDAO, log)
	userService := svc.NewUserService(userRepository, log)
	userHandler := handler.NewUserHandler(userService)
	engine := web.InitWebServer(handlersChain, userHandler)
	return engine
}
