// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gaia-layout/internal/core/repo"
	"gaia-layout/internal/core/repo/dao"
	"gaia-layout/internal/core/svc"
	"gaia-layout/internal/infra"
	"gaia-layout/internal/rpc"
	"gaia-layout/internal/server"
	"github.com/apus-run/gaia"
	"github.com/apus-run/sea-kit/log"
)

// Injectors from wire.go:

// runApp init server application.
func runApp(logger log.Logger) *gaia.Gaia {
	greeterService := rpc.NewGreeterService()
	db := infra.InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repo.NewUserRepository(userDAO, logger)
	userService := svc.NewUserService(userRepository, logger)
	rpcUserService := rpc.NewUserService(userService)
	grpcServer := server.NewGRPCServer(greeterService, rpcUserService)
	httpServer := server.NewHTTPServer(greeterService, rpcUserService)
	gaiaGaia := newApp(logger, grpcServer, httpServer)
	return gaiaGaia
}
